[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
cache_path = "cache"
libs = []
allow_paths = ["../node_modules"]
ignored_error_codes = [6335]
remappings = ["@openzeppelin/contracts/=../node_modules/@openzeppelin/contracts/"]
solc = "0.8.36"
evm_version = "osaka"
optimizer = true
optimizer_runs = 200
bytecode_hash = "ipfs"
cbor_metadata = true

[fuzz]
runs = 512

[invariant]
runs = 128
depth = 64
fail_on_revert = false

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "long"


[lint]
exclude_lints = ["block-timestamp"]
