/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false worker/env.d.ts` (hash: f00d31e107bf445a55e7c5f851a1fadd)
interface __BaseEnv_Env {
	DB: D1Database;
	APP_ENV: string;
	MAINNET_WRITES_ENABLED: string;
	SPONSOR_ENABLED: string;
	X402_TESTNET_ENABLED: string;
	X402_MAINNET_ENABLED: string;
	SIWE_ALLOWED_DOMAIN: string;
	SIWE_ALLOWED_ORIGIN: string;
	SIWE_CHAIN_IDS: string;
	SESSION_HASH_SECRET: string;
	IP_BUCKET_HMAC_SECRET: string;
	SPONSOR_ID_HMAC_SECRET: string;
	TURNSTILE_SECRET_KEY: string;
	CDP_PAYMASTER_URL: string;
	CDP_PROJECT_ID: string;
	CDP_API_KEY_ID: string;
	CDP_API_KEY_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ENV" | "MAINNET_WRITES_ENABLED" | "SPONSOR_ENABLED" | "X402_TESTNET_ENABLED" | "X402_MAINNET_ENABLED" | "SIWE_ALLOWED_DOMAIN" | "SIWE_ALLOWED_ORIGIN" | "SIWE_CHAIN_IDS" | "SESSION_HASH_SECRET" | "IP_BUCKET_HMAC_SECRET" | "SPONSOR_ID_HMAC_SECRET" | "TURNSTILE_SECRET_KEY" | "CDP_PAYMASTER_URL" | "CDP_PROJECT_ID" | "CDP_API_KEY_ID" | "CDP_API_KEY_SECRET">> {}
}
