/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false worker/env.d.ts` (hash: 16337656e250c2c76e7ad8093b6a9a71)
interface __BaseEnv_Env {
	DB: D1Database;
	APP_ENV: "production";
	SPONSOR_ENABLED: "true";
	X402_TESTNET_ENABLED: "false";
	X402_MAINNET_ENABLED: "false";
	SIWE_ALLOWED_DOMAIN: "basestamp-web.ndun000.workers.dev";
	SIWE_ALLOWED_ORIGIN: "https://basestamp-web.ndun000.workers.dev";
	SIWE_CHAIN_IDS: "84532,8453";
	SECURITY_CONTACT_URL: "";
	SPONSOR_POLICY_VERSION: "2";
	SPONSOR_ALLOWED_ORIGINS: "https://keys.coinbase.com";
	TURNSTILE_ALLOWED_HOSTNAMES: "basestamp-web.ndun000.workers.dev";
	SESSION_HASH_SECRET: string;
	BASE_BUILDER_CODE: string;
	CDP_PAYMASTER_URL: string;
	IP_BUCKET_HMAC_SECRET: string;
	SPONSOR_ID_HMAC_SECRET: string;
	TURNSTILE_SECRET_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ENV" | "SPONSOR_ENABLED" | "X402_TESTNET_ENABLED" | "X402_MAINNET_ENABLED" | "SIWE_ALLOWED_DOMAIN" | "SIWE_ALLOWED_ORIGIN" | "SIWE_CHAIN_IDS" | "SECURITY_CONTACT_URL" | "SPONSOR_POLICY_VERSION" | "SPONSOR_ALLOWED_ORIGINS" | "TURNSTILE_ALLOWED_HOSTNAMES" | "SESSION_HASH_SECRET" | "BASE_BUILDER_CODE" | "CDP_PAYMASTER_URL" | "IP_BUCKET_HMAC_SECRET" | "SPONSOR_ID_HMAC_SECRET" | "TURNSTILE_SECRET_KEY">> {}
}
