/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false worker/env.d.ts` (hash: 685fcd300d393e59afb7bb203334daf8)
interface __BaseEnv_Env {
	DB: D1Database;
	APP_ENV: "production";
	MAINNET_WRITES_ENABLED: "false";
	SPONSOR_ENABLED: "false";
	X402_TESTNET_ENABLED: "false";
	X402_MAINNET_ENABLED: "false";
	SIWE_ALLOWED_DOMAIN: "basestamp-web.ndun000.workers.dev";
	SIWE_ALLOWED_ORIGIN: "https://basestamp-web.ndun000.workers.dev";
	SIWE_CHAIN_IDS: "84532,8453";
	SESSION_HASH_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ENV" | "MAINNET_WRITES_ENABLED" | "SPONSOR_ENABLED" | "X402_TESTNET_ENABLED" | "X402_MAINNET_ENABLED" | "SIWE_ALLOWED_DOMAIN" | "SIWE_ALLOWED_ORIGIN" | "SIWE_CHAIN_IDS" | "SESSION_HASH_SECRET">> {}
}
